os:
  - osx
osx_image: xcode7.3

language: node_js

node_js:
  - '7'

before_install:
  - npm config delete prefix

install:
  - rm -rf node_modules
  - npm i -g npm@3
  - npm install

branches:
  except:
    - website

script:
  - export DEBUG=electron*
  - npm run test
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./sig/import.sh && npm run make:darwin && node ./sig/publish-mac.js; fi
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then npm run package:darwin; fi
  - npm run test-electron-coverage
  - npm run _coveralls
  - npm run _coverage_publish
  # Disabel Spectron for now
  # - npm run test-spectron

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/92deafd1eb3a9871497b
    on_success: always
    on_failure: always
    on_start: never
