os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.electron

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
  - source ~/.bashrc
  - nvm install 4.2.2
  - nvm use 4.2.2
  - npm install

script:
  - npm run test
  - npm run package:darwin
