version: 1.0.{build}
environment:
  nodejs_version: "4.4.1"
  GITHUB_KEY:
    secure: eZcSozzDKzRJhSoXL7LS9w1jqFLdkiRT4H57JoWGpKj/kS6NC/DP3ColwKkvSeFn
  SIGN_CERT_PASS:
    secure: UEVPxVtsn5UnAi3PhhkUSA==
  GPMDP_LASTFM_API_KEY:
    secure: t4Ka6QT10/i0FMX4cVi4BaNeGKfi76T/iEKZ3PEsnUPrQ2lK6cmlGSA01NfHvUze
  GPMDP_LASTFM_API_SECRET:
    secure: RIfJtcbYwHBG7uGI8TQS9JzO37zPNuyO3yPPayVKb8vVISfxrFXH4rYT9dzmGaAx

branches:
  except:
  - website

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - npm install
  - npm upgrade

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build_script:
- cmd: npm run make:win

artifacts:
  - path: 'dist\installers\win32\Google Play Music Desktop PlayerSetup.exe'
