version: 1.0.{build}
environment:
  nodejs_version: "6.1.0"
  GITHUB_KEY:
    secure: eZcSozzDKzRJhSoXL7LS9w1jqFLdkiRT4H57JoWGpKj/kS6NC/DP3ColwKkvSeFn
  SIGN_CERT_PASS:
    secure: UEVPxVtsn5UnAi3PhhkUSA==
  GPMDP_LASTFM_API_KEY:
    secure: t4Ka6QT10/i0FMX4cVi4BaNeGKfi76T/iEKZ3PEsnUPrQ2lK6cmlGSA01NfHvUze
  GPMDP_LASTFM_API_SECRET:
    secure: RIfJtcbYwHBG7uGI8TQS9JzO37zPNuyO3yPPayVKb8vVISfxrFXH4rYT9dzmGaAx
  GOOGLE_MUSIC_JS_EMAIL:
    secure: UtCUPcatc43rCKYKuQUl+Q==
  GOOGLE_MUSIC_JS_PASSWORD:
    secure: ysdUmqSIrW+4OE1sRvLp+g==
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'

branches:
  except:
  - website

os: unstable
platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - rd /S /Q "node_modules"
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjourcore2.msi
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - npm cache clean
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run test-unit
  - npm run test-spec

build_script:
- cmd: npm run make:win

artifacts:
  - path: 'dist\installers\win32\Google Play Music Desktop PlayerSetup.exe'
